# Dockerfile.dev
FROM node:20-alpine AS base

# Instalação do pnpm globalmente
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

# Estágio de desenvolvimento
FROM base AS development
COPY package.json pnpm-lock.yaml ./

# Instala todas as dependências (incluindo devDependencies)
RUN pnpm install

# Copia o código e os arquivos do Prisma para gerar o client
COPY . .
RUN pnpm prisma generate

# O comando 'pnpm dev' é passado pelo docker-compose
EXPOSE 3000
EXPOSE 5555